#!/bin/bash

source "$(dirname $0)/../closhell"
test_dir="$closhell_run_dir"/test

prepare_suite "call"

after() {
	rm -rf "$test_dir"/test_file_*
}

test_case "call executes closure" "$(cat <<-TEST
	# given
	closure="$(cat <<-BODY
		touch \"$test_dir/test_file_apply\\\$1.tmp\"
		touch \"$test_dir/test_file_apply\\\$2.tmp\"
		touch \"$test_dir/test_file_apply\\\$3.tmp\"
		touch \"$test_dir/test_file_apply\\\$4.tmp\"
		touch \"$test_dir/test_file_apply\\\$5.tmp\"
		return 100
	BODY
	)"

	# when
	call "\$closure" "a" "b" "c" "d" "e"

	# then
	assert_equal \$? 100
	cat "$test_dir"/test_file_applya.tmp "$test_dir"/test_file_applyb.tmp "$test_dir"/test_file_applyc.tmp \
	    "$test_dir"/test_file_applyd.tmp "$test_dir"/test_file_applye.tmp > /dev/null
TEST
)"

finish_suite
