#!/bin/bash

apply() (
	copy=("$@")
	argc=$(expr $# - 1)
	argv=${@:1:$argc}
	body=${copy[-1]}
	block() {
		(eval "$body")
	}
	block $argv
)

apply0() (
	body=$1
	block() {
		(eval "$body")
	}
	block
)

apply1() (
	body=$2
	block() {
		(eval "$body")
	}
	block "$1"
)

apply2() (
	body=$3
	block() {
		(eval "$body")
	}
	block "$1" "$2"
)

apply3() (
	body=$4
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3"
)

apply4() (
	body=$5
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4"
)

apply5() (
	body=$6
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5"
)

apply6() (
	body=$7
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5" "$6"
)


apply7() (
	body=$8
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5" "$6" "$7"
)

apply8() (
	body=$9
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
)

apply9() (
	body=${10}
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
)

apply10() (
	body=${11}
	block() {
		(eval "$body")
	}
	block "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}"
)
