#!/bin/bash

export suite_name=
export suite_overall_tests=0
export suite_successful_tests=0
export suite_failed_tests=0

noop() {
	echo > /dev/null
}

run_before() {
	declare -f before > /dev/null
	if [ $? -eq 0 ]; then
		before
	else
		noop
	fi
}

run_after() {
	declare -f after > /dev/null
	if [ $? -eq 0 ]; then
		after
	else
		noop
	fi
}

prepare_suite() {
	export suite_name="$1"
	export suite_overall_tests=0
	export suite_successful_tests=0
	export suite_failed_tests=0
	echo "Starting suite $1"
}

test_case() {
	echo "  - $1"
	run_before
	noop # to make sure that empty body always returns 0
	eval "$2"
	if [ $? -eq 0 ]; then
		export suite_successful_tests=$((suite_successful_tests+1))
		echo "    [success]"
	else
		export suite_failed_tests=$((suite_failed_tests+1))
		echo "    [failure]"
	fi
	export suite_overall_tests=$((suite_overall_tests+1))
	run_after
}

finish_suite() {
	echo "Test suite for $suite_name"
	echo "  Results:"
	echo "  Successful: $suite_successful_tests, Failed: $suite_failed_tests, Overall: $suite_overall_tests"
	if [ $suite_failed_tests -eq 0 ]; then
		exit 0
	else
		exit 1
	fi
}

assert_equal() {
	if [ $1 -eq $2 ]; then
		return 0
	else
		echo "    assertion failed: $1 != $2"
		return 1
	fi
}
